services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=/api
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api

  api:
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: api/Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=db;Database=MessageRDB;User=sa;Password=Your_password123;Encrypt=false;
      - JWT__SECRET=YwN7c!@#m02zL*sd82lMk!adwaf4d2rg
      - JWT__ISSUER=trecplans.local
      - JWT__AUDIENCE=trecplans_user
      - ACCESS_TOKEN_EXPIRE_MIN=15
      - REFRESH_TOKEN_EXPIRE_MIN=20160
    depends_on:
      - db



  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - message_sqlserver_data:/var/opt/mssql

volumes:
  message_sqlserver_data:
