services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  api:
    build: ./api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MessageRDB;User=sa;Password=Your_password123;
      - Redis__Host=redis
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - JWT__Secret=YwN7c!@#m02zL*sd82lMk!adwaf4d2rg
      - ACCESS_TOKEN_EXPIRE_MIN=15
      - REFRESH_TOKEN_EXPIRE_MIN=20160
    depends_on:
      - db
      - redis
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - message_sqlserver_data:/var/opt/mssql

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  message_sqlserver_data:
  redis_data:
