CREATE DATABASE AuthRDB;
USE AuthRDB;

CREATE TABLE Users (
    UserCommonId VARCHAR(16) PRIMARY KEY,
    Email NVARCHAR(256) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(512) NOT NULL,
    PasswordSalt NVARCHAR(512) NOT NULL,
    DisplayName NVARCHAR(100),
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2
);
 
 CREATE TABLE Clients (
    ClientId VARCHAR(64) PRIMARY KEY,
    ClientName NVARCHAR(100) NOT NULL,
	ClientSecret NVARCHAR(256) NOT NULL,
    Description NVARCHAR(255),
    CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE UserData (
    UserCommonId VARCHAR(16) NOT NULL,
    ClientId VARCHAR(64) NOT NULL,
    DataKey NVARCHAR(100) NOT NULL,
    DataValue NVARCHAR(MAX),
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2,
    PRIMARY KEY (UserCommonId, ClientId, DataKey),
    FOREIGN KEY (UserCommonId) REFERENCES Users(UserCommonId) ON DELETE CASCADE,
    FOREIGN KEY (ClientId) REFERENCES Clients(ClientId) ON DELETE CASCADE
);

CREATE TABLE ClientDataKeys (
    ClientId VARCHAR(64) NOT NULL,
    DataKey NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255),
    IsRequired BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (ClientId, DataKey),
    FOREIGN KEY (ClientId) REFERENCES Clients(ClientId) ON DELETE CASCADE
);
