// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace backend.Models;

public partial class AuthRDBContext : DbContext
{
    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientDataKey> ClientDataKeys { get; set; }

    public virtual DbSet<TrainingMenu> TrainingMenus { get; set; }

    public virtual DbSet<TrainingRecordSet> TrainingRecordSets { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDatum> UserData { get; set; }

    public virtual DbSet<UserToken> UserTokens { get; set; }

    private readonly string _ConnectionStr;

    public AuthRDBContext(string argConnectionStr)
    {
        _ConnectionStr = argConnectionStr;
    }

    public AuthRDBContext(DbContextOptions<AuthRDBContext> options) : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(_ConnectionStr);
        }
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Clients__E67E1A24311898F3");

            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ClientSecret)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<ClientDataKey>(entity =>
        {
            entity.HasKey(e => new { e.ClientId, e.DataKey }).HasName("PK__ClientDa__10DFDE96BF542813");

            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.DataKey).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsRequired).HasDefaultValue(false);

            entity.HasOne(d => d.Client).WithMany(p => p.ClientDataKeys)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK__ClientDat__Clien__44FF419A");
        });

        modelBuilder.Entity<TrainingMenu>(entity =>
        {
            entity.HasKey(e => e.MenuId).HasName("PK__Training__C99ED230A009F735");

            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TrainingRecordSet>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.MenuId, e.TrainingDate, e.SetNumber }).HasName("PK__Training__3532352C5FE282CD");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Menu).WithMany(p => p.TrainingRecordSets)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingR__MenuI__4BAC3F29");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.TrainingRecordSets)
                .HasForeignKey(d => d.UserCommonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingR__UserC__4CA06362");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserCommonId).HasName("PK__Users__29D0965E4529C1D0");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105346AB3F5DC").IsUnique();

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasMaxLength(512);
        });

        modelBuilder.Entity<UserDatum>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.ClientId, e.DataKey }).HasName("PK__UserData__58DD6BB7DC37DE30");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.DataKey).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Client).WithMany(p => p.UserData)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK__UserData__Client__403A8C7D");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.UserData)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK__UserData__UserCo__3F466844");
        });

        modelBuilder.Entity<UserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.ClientId }).HasName("PK__UserToke__77B777FCD770EA72");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.RefreshToken)
                .IsRequired()
                .HasMaxLength(512);

            entity.HasOne(d => d.Client).WithMany(p => p.UserTokens)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK__UserToken__Clien__5165187F");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.UserTokens)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK__UserToken__UserC__5070F446");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}