// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class ClientDataKey
{
    public string ClientId { get; set; }

    public string DataKey { get; set; }

    public string Description { get; set; }

    public bool? IsRequired { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Client Client { get; set; }
}