// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class TrainingRecordSet
{
    public string UserCommonId { get; set; }

    public string MenuId { get; set; }

    public DateOnly TrainingDate { get; set; }

    public int SetNumber { get; set; }

    public int Reps { get; set; }

    public decimal? Weight { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual TrainingMenu Menu { get; set; }

    public virtual User UserCommon { get; set; }
}