// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class UserDatum
{
    public string UserCommonId { get; set; }

    public string ClientId { get; set; }

    public string DataKey { get; set; }

    public string DataValue { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Client Client { get; set; }

    public virtual User UserCommon { get; set; }
}