// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models;

public partial class User
{
    public string UserCommonId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string DisplayName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<TrainingRecordSet> TrainingRecordSets { get; set; } = new List<TrainingRecordSet>();

    public virtual ICollection<UserDatum> UserData { get; set; } = new List<UserDatum>();

    public virtual ICollection<UserToken> UserTokens { get; set; } = new List<UserToken>();
}