// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class Client
{
    public string ClientId { get; set; }

    public string ClientName { get; set; }

    public string ClientSecret { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ClientDataKey> ClientDataKeys { get; set; } = new List<ClientDataKey>();

    public virtual ICollection<UserDatum> UserData { get; set; } = new List<UserDatum>();
}