// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class DailyTrainingRecord
{
    public string UserCommonId { get; set; }

    public string MenuId { get; set; }

    public DateOnly TrainingDate { get; set; }

    public int SetCount { get; set; }

    public int MaxReps { get; set; }

    public decimal? MaxRepsWeight { get; set; }

    public int? MaxWeightReps { get; set; }

    public decimal? MaxWeight { get; set; }

    public decimal? TotalLoadAmount { get; set; }

    public int TotalReps { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual TrainingMenu Menu { get; set; }

    public virtual User UserCommon { get; set; }
}