// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class TagMaster
{
    public string TagId { get; set; }

    public string Jpname { get; set; }

    public string Enname { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<TrainingTag> TrainingTags { get; set; } = new List<TrainingTag>();
}