// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class TrainingMenu
{
    public string MenuId { get; set; }

    public string Jpname { get; set; }

    public string Enname { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<DailyTrainingRecord> DailyTrainingRecords { get; set; } = new List<DailyTrainingRecord>();

    public virtual ICollection<TrainingRecordSet> TrainingRecordSets { get; set; } = new List<TrainingRecordSet>();

    public virtual ICollection<TrainingTag> TrainingTags { get; set; } = new List<TrainingTag>();
}