// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Api.Models;

public partial class TrecPlansRDBContext : DbContext
{
    public TrecPlansRDBContext(DbContextOptions<TrecPlansRDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientDataKey> ClientDataKeys { get; set; }

    public virtual DbSet<DailyTrainingRecord> DailyTrainingRecords { get; set; }

    public virtual DbSet<TagMaster> TagMasters { get; set; }

    public virtual DbSet<TrainingMenu> TrainingMenus { get; set; }

    public virtual DbSet<TrainingRecordSet> TrainingRecordSets { get; set; }

    public virtual DbSet<TrainingTag> TrainingTags { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDatum> UserData { get; set; }

    public virtual DbSet<UserToken> UserTokens { get; set; }

    public virtual DbSet<SupplementMaster> SupplementMasters { get; set; }

    public virtual DbSet<SupplementIntakeRecord> SupplementIntakeRecords { get; set; }

    public virtual DbSet<SupplementSchedule> SupplementSchedules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Clients__E67E1A245F0454CE");

            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ClientSecret)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<ClientDataKey>(entity =>
        {
            entity.HasKey(e => new { e.ClientId, e.DataKey }).HasName("PK__ClientDa__10DFDE96EA1B08B9");

            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.DataKey).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsRequired).HasDefaultValue(false);

            entity.HasOne(d => d.Client).WithMany(p => p.ClientDataKeys)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK__ClientDat__Clien__44FF419A");
        });

        modelBuilder.Entity<DailyTrainingRecord>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.MenuId, e.TrainingDate }).HasName("PK__DailyTra__65D580151ADB5E26");

            entity.ToTable("DailyTrainingRecord");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.MaxRepsWeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MaxWeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TotalLoadAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Menu).WithMany(p => p.DailyTrainingRecords)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DailyTrai__MenuI__59FA5E80");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.DailyTrainingRecords)
                .HasForeignKey(d => d.UserCommonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DailyTrai__UserC__5AEE82B9");
        });

        modelBuilder.Entity<TagMaster>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__TagMaste__657CF9AC73C202B9");

            entity.ToTable("TagMaster");

            entity.Property(e => e.TagId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Enname)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ENName");
            entity.Property(e => e.Jpname)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("JPName");
        });

        modelBuilder.Entity<TrainingMenu>(entity =>
        {
            entity.HasKey(e => e.MenuId).HasName("PK__Training__C99ED2301C7EE0CC");

            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Enname)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ENName");
            entity.Property(e => e.Jpname)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("JPName");
        });

        modelBuilder.Entity<TrainingRecordSet>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.MenuId, e.TrainingDate, e.SetNumber }).HasName("PK__Training__3532352C88CA8CE1");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Menu).WithMany(p => p.TrainingRecordSets)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingR__MenuI__5441852A");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.TrainingRecordSets)
                .HasForeignKey(d => d.UserCommonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingR__UserC__5535A963");
        });

        modelBuilder.Entity<TrainingTag>(entity =>
        {
            entity.HasKey(e => new { e.TagId, e.MenuId }).HasName("PK__Training__79E5148FD8D7AF93");

            entity.ToTable("TrainingTag");

            entity.Property(e => e.TagId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.MenuId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Enname)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ENName");
            entity.Property(e => e.Jpname)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("JPName");

            entity.HasOne(d => d.Menu).WithMany(p => p.TrainingTags)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingT__MenuI__4E88ABD4");

            entity.HasOne(d => d.Tag).WithMany(p => p.TrainingTags)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TrainingT__TagId__4F7CD00D");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserCommonId).HasName("PK__Users__29D0965E61263AEE");

            entity.HasIndex(e => e.LoginId, "UQ__Users__4DDA28192733D75F").IsUnique();

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.LoginId)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasMaxLength(512);
        });

        modelBuilder.Entity<UserDatum>(entity =>
        {
            entity.HasKey(e => new { e.UserCommonId, e.ClientId, e.DataKey }).HasName("PK__UserData__58DD6BB724E5D806");

            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.ClientId)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.DataKey).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Client).WithMany(p => p.UserData)
                .HasForeignKey(d => d.ClientId)
                .HasConstraintName("FK__UserData__Client__403A8C7D");

            entity.HasOne(d => d.UserCommon).WithMany(p => p.UserData)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK__UserData__UserCo__3F466844");
        });

        modelBuilder.Entity<UserToken>(entity =>
        {
            entity.HasKey(e => e.RefreshToken).HasName("PK__UserToke__DEA298DBFAF2D13B");

            entity.Property(e => e.RefreshToken).HasMaxLength(512);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserCommonId)
                .IsRequired()
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.HasOne(d => d.UserCommon).WithMany(p => p.UserTokens)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK__UserToken__UserC__5EBF139D");
        });

        modelBuilder.Entity<SupplementMaster>(entity =>
        {
            entity.HasKey(e => e.SupplementId);

            entity.ToTable("supplement_master");

            entity.Property(e => e.SupplementId).HasColumnName("supplement_id");
            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("user_common_id");
            entity.Property(e => e.SupplementName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("supplement_name");
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("unit");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.User).WithMany(p => p.SupplementMasters)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK_supplement_user");
        });

        modelBuilder.Entity<SupplementIntakeRecord>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.ToTable("supplement_intake_records");

            entity.Property(e => e.RecordId).HasColumnName("record_id");
            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("user_common_id");
            entity.Property(e => e.SupplementId).HasColumnName("supplement_id");
            entity.Property(e => e.IntakeDate)
                .HasColumnType("date")
                .HasColumnName("intake_date");
            entity.Property(e => e.IntakeTime).HasColumnName("intake_time");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.TimingType)
                .HasMaxLength(20)
                .HasColumnName("timing_type");
            entity.Property(e => e.Memo)
                .HasMaxLength(500)
                .HasColumnName("memo");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.User).WithMany(p => p.SupplementIntakeRecords)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK_intake_user");

            entity.HasOne(d => d.Supplement).WithMany(p => p.SupplementIntakeRecords)
                .HasForeignKey(d => d.SupplementId)
                .HasConstraintName("FK_intake_supplement");
        });

        modelBuilder.Entity<SupplementSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId);

            entity.ToTable("supplement_schedules");

            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.UserCommonId)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("user_common_id");
            entity.Property(e => e.SupplementId).HasColumnName("supplement_id");
            entity.Property(e => e.ScheduleTime).HasColumnName("schedule_time");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.TimingType)
                .HasMaxLength(20)
                .HasColumnName("timing_type");
            entity.Property(e => e.DaysOfWeek)
                .HasMaxLength(20)
                .HasColumnName("days_of_week");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Memo)
                .HasMaxLength(500)
                .HasColumnName("memo");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.User).WithMany(p => p.SupplementSchedules)
                .HasForeignKey(d => d.UserCommonId)
                .HasConstraintName("FK_schedule_user");

            entity.HasOne(d => d.Supplement).WithMany(p => p.SupplementSchedules)
                .HasForeignKey(d => d.SupplementId)
                .HasConstraintName("FK_schedule_supplement");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}